services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=jwt_secret_key
      - NODE_PORT=3000
      - NGINX_PORT=8080
    volumes:
      - ./backend:/app
    expose:
      - "3000"
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always
